### PR TITLE
Rearrange docs directory hierarchy

### LINKED ISSUE #116: Reorder docs directory hierarchy
The name of the tool/algorithm should be at the top level of the directory

### PR DESCRIPTION
**Pull request by caleb-johnson**
Closes #116 

The docs are arranged in the least efficient way. The guides for each tool should be closer.

This takes the docs from `docs/[tutorials & how-tos]/tool` to `docs/tool/[tutorials & how-tos]`

### CODE REVIEW

**Review by garrison — APPROVED** [review]
Thanks.  I updated a few more changed paths in 61331b66da0c1f2ed063f11d329a6d11ff10ed3b. If that change looks good to you, feel free to merge.

EDIT: actually, I need to partially revert that change.  I did not realize until now that you did not include "explanation" in the changed directory hierarchy.

**Comment by garrison** [comment]
I'll note that the table of contents still bounces back and forth between the two methods, like

https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/61331b66da0c1f2ed063f11d329a6d11ff10ed3b/docs/index.rst?plain=1#L25-L35

Going forward, with similar motivation to this change, we may want to consider putting circuit cutting tutorials, explanation, and how-tos back-to-back, followed by entanglement forging tutorials, explanation and how-tos.  (We _could_ also swap the overall order of circuit cutting and entanglement forging.)  In any case, I like the API References being all together at the end; I don't think _they_ should be separated.  But let's save this for a follow-up PR if we want to do it.

**Comment by garrison** [comment]
So, why not include "explanation" in the new hierarchy as well?

I think you made the right call with keeping the API docs all together, but I feel more mixed when it comes to explanation.

**Comment by caleb-johnson** [comment]
> I'll note that the table of contents still bounces back and forth between the two methods, like
> 
> https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/61331b66da0c1f2ed063f11d329a6d11ff10ed3b/docs/index.rst?plain=1#L25-L35
> 
> Going forward, with similar motivation to this change, we may want to consider putting circuit cutting tutorials, explanation, and how-tos back-to-back, followed by entanglement forging tutorials, explanation and how-tos. (We _could_ also swap the overall order of circuit cutting and entanglement forging.) In any case, I like the API References being all together at the end; I don't think _they_ should be separated. But let's save this for a follow-up PR if we want to do it.

Ugh ya, this is bugging me now that you mention it. Any reason I cant just rearrange them here in this PR?

**Comment by caleb-johnson** [comment]
> So, why not include "explanation" in the new hierarchy as well?
> 
> I think you made the right call with keeping the API docs all together, but I feel more mixed when it comes to explanation.

Let me see what I can do with explanation...

**Comment by caleb-johnson** [comment]
> So, why not include "explanation" in the new hierarchy as well?
> 
> I think you made the right call with keeping the API docs all together, but I feel more mixed when it comes to explanation.

OK I've moved explanation inside the tools as well and reordered the master index

**Comment by garrison** [comment]
After building the docs locally, I thought that the `maxdepth` should be adjusted from 3 to 2 in `docs/index.rst`.  Otherwise, the table of contents is way too detailed, e.g., it includes every subheading in every tutorial.  I went ahead and adjusted this in 41db2afa2ef9421a54d08a43d72c74842a59d396.

I fixed a few remaining links, too, in 98e3e2176cc392174e1566e86119a932d4835622.

My only remaining comment is that IMO, in both cases, explanation should actually come before how-to guides in the table of contents.  If you haven't learned/understood some of the theoretical background behind a method yet, I think it's unlikely that you'll wonder things like "how do I use asymmetric bitstrings?" or "how do I freeze the orbitals?"

Otherwise, this PR looks good to me.

**Comment by caleb-johnson** [comment]
> After building the docs locally, I thought that the `maxdepth` should be adjusted from 3 to 2 in `docs/index.rst`. Otherwise, the table of contents is way too detailed, e.g., it includes every subheading in every tutorial. I went ahead and adjusted this in [41db2af](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/commit/41db2afa2ef9421a54d08a43d72c74842a59d396).
> 
> I fixed a few remaining links, too, in [98e3e21](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/commit/98e3e2176cc392174e1566e86119a932d4835622).
> 
> My only remaining comment is that IMO, in both cases, explanation should actually come before how-to guides in the table of contents. If you haven't learned/understood some of the theoretical background behind a method yet, I think it's unlikely that you'll wonder things like "how do I use asymmetric bitstrings?" or "how do I freeze the orbitals?"
> 
> Otherwise, this PR looks good to me.

I didn't want to force-push, did you intend to click approve on this PR?

**Comment by garrison** [comment]
I am willing to approve this version, but I was waiting for what you thought of

> My only remaining comment is that IMO, in both cases, explanation should actually come before how-to guides in the table of contents. If you haven't learned/understood some of the theoretical background behind a method yet, I think it's unlikely that you'll wonder things like "how do I use asymmetric bitstrings?" or "how do I freeze the orbitals?"

What do you think?

**Review by garrison — DISMISSED** [review]

**Comment by garrison** [comment]
I was actually thinking explanation should be right after tutorials.

**Review by garrison — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
