### PR TITLE
Remove support for Python 3.7

### PR DESCRIPTION
**Pull request by garrison**
Python 3.7 support is deprecated as of Qiskit 0.40.0, and support for Python 3.7 will be removed entirely from Qiskit for the release that is due in July.  This PR removes support for Python 3.7 even sooner for ckt so that we can begin using features that were introduced in Python 3.8, such as [positional-only parameters](https://peps.python.org/pep-0570/).  Since we advertise this project as having alpha status and explicitly [don't follow Qiskit's deprecation policy](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox#deprecation-policy), I think we can get away without providing much in the way of advance notice for dropping Python 3.7.

- [x] Assuming we merge #87, we'll want to revert it on this branch before merging this.

### CODE REVIEW

**Comment by caleb-johnson** [comment]
Is this ready for review?

**Review by caleb-johnson — APPROVED** [review]
Looks GTM, loving the release notes :)

**Review by caleb-johnson — APPROVED** [review]
Looks good, thanks

Should we create an issue for adding support for 3.11?

**Comment by garrison** [comment]
> Should we create an issue for adding support for 3.11?

Support for Python 3.11 will be added by #109.  It's essentially our only path to Python 3.11 support, unless a new cplex release were to work on Python 3.11.

**Pull request merged**
